#!/usr/bin/env bash

# Configuración de la Barra (Estética Hyprland)
sketchybar --bar height=34 \
                 blur_radius=30 \
                 position=top \
                 padding_left=15 \
                 padding_right=15 \
                 color=0xbb24273a \
                 corner_radius=12 \
                 margin=15 \
                 y_offset=12

# Configuración de los Items
sketchybar --default icon.font="JetBrainsMono Nerd Font:Bold:16.0" \
                     label.font="JetBrainsMono Nerd Font:Bold:13.0" \
                     icon.color=0xffcba6f7 \
                     label.color=0xffffffff \
                     padding_left=10 \
                     padding_right=10

# Reloj
sketchybar --add item clock right \
           --set clock update_freq=10 \
           --set clock script="sketchybar --set \$NAME label=\"\$(date '+%H:%M')\"" \
           --set clock icon=󱑂

sketchybar --update
